name: Integration Tests

on:
  push:
    # branches: [ main, develop ]
    branches: [ task-management-aiden ]
  pull_request:
    # branches: [ main, develop ]
    branches: [ task-management-aiden ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            little_farms/backend/package-lock.json
            tests/package-lock.json
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Install backend dependencies
        working-directory: ./little_farms/backend
        run: npm ci
      
      - name: Install test dependencies
        working-directory: ./tests
        run: npm install
      
      - name: Create test environment file
        working-directory: ./little_farms/backend
        run: |
          cat > .env.test << EOF
          FIREBASE_PROJECT_ID=test-project
          FIRESTORE_EMULATOR_HOST=localhost:8080
          NODE_ENV=test
          PORT=3002
          EOF
      
      - name: Start Firestore Emulator
        run: |
          firebase emulators:start --only firestore,auth --project=test-project &
          sleep 10
          echo "Firebase emulators started"
      
      - name: Wait for Firestore Emulator
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 1; done' || echo "Emulator ready"
      
      - name: Run integration tests
        working-directory: ./tests
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
          NODE_ENV: test
        run: npm test -- --coverage --ci
      
      - name: Generate coverage report
        working-directory: ./tests
        run: npm run test:coverage || true
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./tests/coverage/lcov.info
          flags: integration-tests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Comment PR with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const testResults = '✅ Integration tests passed!';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Test Results\n\n${testResults}\n\nNode.js version: ${{ matrix.node-version }}`
            });
      
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-node-${{ matrix.node-version }}
          path: |
            tests/coverage/
            tests/*.log
          retention-days: 30
      
      - name: Stop Firestore Emulator
        if: always()
        run: |
          pkill -f "firebase.*emulators" || true

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
      - name: Check test results
        run: |
          if [ "${{ needs.test.result }}" == "success" ]; then
            echo "✅ All tests passed!"
            exit 0
          else
            echo "❌ Some tests failed"
            exit 1
          fi
